global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # 语音助手服务端监控
  - job_name: 'voice-assistant-server'
    static_configs:
      - targets: ['voice-assistant-server:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s

  # Prometheus自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 系统监控 (如果安装了node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 