version: '3.8'

services:
  # 语音助手服务端
  voice-assistant-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voice-assistant-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 配置文件挂载
      - ./config:/app/config:ro
      # 模型文件挂载（持久化）
      - voice_models:/app/models
      # 日志文件挂载
      - ./logs:/app/logs
      # 缓存目录（ChatTTS模型缓存）
      - voice_cache:/home/app/.cache
    environment:
      # 环境变量
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - TZ=Asia/Shanghai
    networks:
      - voice-assistant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  # 监控服务（可选）
  prometheus:
    image: prom/prometheus:latest
    container_name: voice-assistant-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - voice-assistant-network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: voice-assistant-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin123}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - voice-assistant-network
    profiles:
      - monitoring

# 网络配置
networks:
  voice-assistant-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 数据卷配置
volumes:
  # 模型文件存储
  voice_models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/models
  
  # 缓存目录
  voice_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/cache
  
  # 监控数据
  prometheus_data:
    driver: local
  
  grafana_data:
    driver: local 